# Generated by Django 4.2.10 on 2024-03-03 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0002_alter_movies_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='user',
        ),
    ]
